/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module checker_20 (
    input [15:0] alu_input,
    input [5:0] alufn,
    input [15:0] a,
    input [15:0] b,
    output reg truth
  );
  
  
  
  wire [16-1:0] M_alu_out;
  reg [6-1:0] M_alu_alufn;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  alu_unit_21 alu (
    .alufn(M_alu_alufn),
    .a(M_alu_a),
    .b(M_alu_b),
    .out(M_alu_out)
  );
  
  always @* begin
    M_alu_alufn = alufn;
    M_alu_a = a;
    M_alu_b = b;
    truth = alu_input == M_alu_out;
  end
endmodule
